### ISSUE TITLE
Wrong data file is opened when I import 2019_agsec5a

### ISSUE THREAD

**Issue by KieranCDouglas** [AIDELabAZ/weather_and_agriculture#16]
When I attempt to import 2019_agsec5a, it works but the data it opens is from 2014/2015 rather than 2019. 

<img width="420" alt="Screenshot 2024-04-15 at 1 28 08 PM" src="https://github.com/AIDELabAZ/arec_596/assets/143770423/23995794-ae5e-4ee9-af74-3b021aeffd93">
<img width="634" alt="Screenshot 2024-04-15 at 1 27 28 PM" src="https://github.com/AIDELabAZ/arec_596/assets/143770423/d086f974-b64b-4cdb-884e-f39e224419d6">

**Comment by jdavidm** [comment]
So the issue is that you define the paths as `local` but then reference those paths with the symbol for a global `$`. Therefore, when you ask it to load `agsec51.dta` Stata still has in its memory the path to the last global defined as `$root`. When I change the `loc` to `global` in the paths, the correct data file is loaded.

I'll discard my changes on this branch at let you make the changes and verify that it runs. If that doesn't fix it for you, reopen this issue and let me know what errors you are getting.

**Comment by KieranCDouglas** [comment]
Got it working, thank you!
